version: "2.0"

services:
  cowrie:
    restart: always
    # Bug Michel to create a Docker Hub account and build an image from the repo.
    # build: .
    image: cafuego/cowrie:dev
    ports:
      - "2222:2222"
      - "2223:2223"
